#Piadas que serão contadas pelo JARVIS de forma aleatoria
piadas = [
    ["Por que a aranha é o animal mais carente do mundo?","Porque ela é um Aracneedyou"],
    ["Por que o pinheiro não se perde na floresta?","Porque ele tem uma pinha"],
    ["Sabe como é a piada do pintinho caipira?","pir"],
    ["O que o pagodeiro foi fazer na igreja?","foi cantar pá gódi"],
    ["Por que o Napoleão era sempre chamado para festas na França?","Porque ele era bom na párty"],
    ["O que aconteceu com os lápis quando souberam que o dono da Faber Castell morreu?","Eles ficaram desapontados"],
    ["A plantinha foi ao hospital, mas não foi atendida. Por quê?","Porque só tinha médico de plantão"],
    ["Você conhece a piada do pônei?","Pô nem eu"],
    ["Qual a fórmula da água benta?","H deus ó"],
    ["Qual o rei dos queijos?","É o reiqueijão"],
    ["O que o paro falou pra pata?","Vem quá"],
    ["Por que a velinha não usa relógio?","Porque ela é sem hora"],
    ["O que a vaca disse pro boi?","Te amuuuuuuuuuuuu"],
    ["O que a xuxa foi fazer no bar?","Foi beber ca sasha"],
    ["Havia dois caminhões voando. Um caiu. Por que o outro continuou vioando?","Porque era caminhão-pipa"],
    ["Por que a formiga tem quatro patas?","Porque se tivesse cinco se chamaria faivemiga"],
    ["Quando os americanos comeram carne pela primeira vez?","Quando chegou Cristovão com lombo"],
    ["Qual nome do carro que indica que vai chover?","O celta preto"],
    ["Uma loira pintou o cabelo de preto. Qual nome do filme?","Inteligência artificial"],
    ["Por que o jácaré tirou o filho da escola?","porque ele repetil de ano"],
    ["Qual o animal que não vale mais nada?","O javali"],
    ["Por que o bombeiro não gosta de andar?","Porque ele sócorre"],
    ["Qual a tecla preferida do astronauta?","O espaço"],
    ["Por que a água foi presa?","porque ela matou a sede"],
    ["Qual remédio avisa quando você está bebendo demais?","O paracetamal"],
    ["Qual cidade brasileira que não existe taxi?","Ubêrlandia"],
]